config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  # resources :items
  resources :users, only: [:show,:index]
  resources :images
  resources :destinations
  resources :purchases
  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'cards#pay'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :items do
  #   #Ajaxで動くアクションのルートを作成
  #   collection do
  #     get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
  #     get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
  #   end
  #   member do
  #     post 'buy', to: 'items#buy'
  #     get 'done', to: 'items#done'
  #   end
  # end

  resources :items do
    resources :purchases, only: [:index] do
      collection do
        get 'done', to: 'purchases#done'
        post 'buy', to: 'purchases#buy'
      end
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get "select_category_index"
      get 'search'
      get 'all'
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  # resources :categories, only: [:index] do
  #   member do
  #     get 'parent'
  #     get 'child'
  #     get 'grandchild'
  #   end
  # end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, :family_name, :first_name, :family_name_kana, :first_name_kana, :birth_day, presence: true

  has_many :destinations, dependent: :destroy
  has_many :cards, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :selling_items, -> { where("buyer_id is NULL") }, foreign_key: "seller_id", class_name: "Item"
  has_many :bought_items, class_name: "Item", foreign_key: "buyer_id"
  has_many :sold_items, -> { where("buyer_id is not NULL") }, foreign_key: "seller_id", class_name: "Item"

  # パスワード英字数字１文字かつ７文字以上のバリデーション↓
  validates :password, format: { with:/\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{7,100}+\z/i}
  # 全角のバリデーション↓
  validate :name_em
  validate :name_kana_em
  # メールアドレスのバリデーション↓
  validate :valid_email?


  def valid_email?
    return if email.blank? || email =~ /^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
    # blank?はblankであれば"true"でblankでなければ"flase"を返す
    # ||は"または"であり左側が"false"なら右側を"return"する
    # つまり"email.blank?"が"false(ブランクではない)"場合、"email"を正規表現にかけるということになる
  end

  # 別に使用予定の可能性があるためいったんコメントアウト
  
  # def encrypted_password
  #   # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a

    # return if password.blank? || password =~ /^(?=.*?[a-zA-Z])(?=.*?[0-9]).{7,70}$/

  #   # blank?-値がない状態がture
  #   errors.add :password, "は英字と数字をそれぞれ1文字以上含める必要があります"
  #   # password.blank? || password =~ のどちらも"false"だからエラーになり、エラー表示される
  # end

  def name_em
    if !(family_name =~ /^[ぁ-んァ-ン一-龥]/)
      if !(first_name =~ /^[ぁ-んァ-ン一-龥]/)
        errors.add :family_name, "は全角で入力してください"
        errors.add :first_name, "は全角で入力してください"
      else
        errors.add :family_name, "は全角で入力してください"
      end
    elsif !(first_name =~ /^[ぁ-んァ-ン一-龥]/)
      errors.add :first_name, "は全角で入力してください"
    else
      return
    end
  end

  def name_kana_em
    if !(family_name_kana =~ /^([ァ-ン]|ー)+$/)
      if !(first_name_kana =~ /^([ァ-ン]|ー)+$/)
        errors.add :family_name_kana, "は全角カタカナで入力してください"
        errors.add :first_name_kana, "は全角カタカナで入力してください"
      else
        errors.add :family_name_kana, "は全角カタカナで入力してください"
      end
    elsif !(first_name_kana =~ /^([ァ-ン]|ー)+$/)
      errors.add :first_name_kana, "は全角カタカナで入力してください"
    else
      return
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @parents = Category.where(ancestry: nil)    
    @items = Item.where(seller_id: current_user.id)
  end

  def show
    @parents = Category.where(ancestry: nil)
  end

  def new
    @user = User.new
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_myitem.html.haml
-# 新着アイテムページ
- @items.each do |item|
  -if item.buyer_id.nil?
    = link_to item_path(item.id),class: "postlink" do
      .postTitle
        .postImage
          = image_tag item.images[0].image.url, class: "postImage__itemimage" 
        .post_date
          = item.created_at.strftime('%Y/%m/%d')
          出品
          .Post__postText
            =item.name
  -else
    .postTitle
      .postImage
        = image_tag item.images[0].image.url, class: "postImage__itemimage" 
      .post_date
        = item.created_at.strftime('%Y/%m/%d')
        出品
        .Post__postText
          .buyercomp 売却されました

-# = link_to item_path(item.id) do
  -#   .postTitle
  -#     .postImage
  -#       = image_tag item.images[0].image.url, class: "postImage__itemimage" 
  -#     .post_date
  -#       = item.created_at.strftime('%Y/%m/%d')
  -#       出品
  -#       .Post__postText
  -#       -if item.buyer_id.nil?
  -#         = link_to item.name, item_path(item.id),class: "postText__nametext"
  -#       - else
  -#         .buyercomp 売却されました

app/views/users/_options.html.haml
-# マイページの左部分
%nav.mypage-main__left__nav
  %h3.mypage-main__left__nav__head マイページ
  %ul.mypage-main__left__list
    %li
      = link_to "発送元・お届け先住所変更", new_destination_path, class: "mypage-main__left__nav__list__item"
      -# = link_to "発送元・お届け先住所変更", edit_destination_path(current_user), class: "mypage-main__left__nav__list__item"

    %li
      = link_to "支払い方法", new_card_path, class: "mypage-main__left__nav__list__item", data: { turbolinks: false}
    -# %li
    -#   %a.mypage-main__left__nav__list__item{:href => "#"}
    -#     メール/パスワード
    %li
      = link_to "本人情報", edit_user_registration_path, class: "mypage-main__left__nav__list__item"
    -#  %i.fas.fa-chevron-right
    %li
      = link_to "ログアウト", user_path(current_user), class: "mypage-main__left__nav__list__item"
    %li
      = link_to "出品確認", users_path(current_user), class: "mypage-main__left__nav__list__item"

app/views/users/index.html.haml
= render "layouts/header"
.mypage-main
  .mypage-main__left
    = render "users/options"
  .mypage-main__right
    .mypage-main__right__title 
      = render partial: "myitem", locals: {images: @items}
= render "layouts/footer"

app/views/users/show.html.haml
-# ログアウト
= render "layouts/header"
.mypage-main
  .mypage-main__left
    = render "options"
  .mypage-main__right
    .mypage-main__right__title
      %h1 ログアウト
    .mypage-main__right__main
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "mypage-main__right__main__logout"
= render "layouts/footer"

-# .mypage-top
-#   %h1 マイページ
-# .mypage-main
-#   .mypage-main__left
-#     %nav.mypage-main__left__nav
-#       %h3.mypage-main__left__nav__head 詳細
-#       %ul.mypage-main__left__list
-#         %li
-#           %a.mypage-main__left__nav__list__item.active{:href => "#"}
-#             プロフィール
-#             %i.fas.fa-chevron-right
-#         %li
-#           %a.mypage-main__left__nav__list__item{:href => "#"}
-#             発送元・お届け先住所変更
-#             %i.fas.fa-chevron-right
-#         %li
-#           -# %a.mypage-main__left__nav__list__item{:href => "#"}
-#           -#   支払い方法
-#           -#   %i.fas.fa-chevron-right
-#           = link_to "支払い方法", new_card_path, class: "mypage-main__left__nav__list__item"
-#           %i.fas.fa-chevron-right
-#         %li
-#           %a.mypage-main__left__nav__list__item{:href => "#"}
-#             メール/パスワード
-#             %i.fas.fa-chevron-right
-#         %li
-#           %a.mypage-main__left__nav__list__item{:href => "#"}
-#             本人情報
-#             %i.fas.fa-chevron-right
-#         %li
-#           %a.mypage-main__left__nav__list__item{:href => "#"}
-#             電話番号の確認
-#             %i.fas.fa-chevron-right
-#         -# %li
-#         -#   %a.mypage-main__left__nav__list__item{:href => "#"}
-#         -#     ログアウト
-#         -#     %i.fas.fa-chevron-right
-#         %li
-#           = link_to "ログアウト", user_path(current_user), class: "mypage-main__left__nav__list__item"
-#           %i.fas.fa-chevron-right
-#   .mypage-main__right
-#     .mypage-main__right__title
-#       %h1 ログアウト
-#     .mypage-main__right__main
-#       = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "mypage-main__right__main__logout"
-#       -# %button.mypage-main__right__main__logout{:type => "submit"} ログアウト