config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  # resources :items
  resources :users, only: [:show,:index]
  resources :images
  resources :destinations
  resources :purchases
  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'cards#pay'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :items do
  #   #Ajaxで動くアクションのルートを作成
  #   collection do
  #     get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
  #     get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
  #   end
  #   member do
  #     post 'buy', to: 'items#buy'
  #     get 'done', to: 'items#done'
  #   end
  # end

  resources :items do
    resources :purchases, only: [:index] do
      collection do
        get 'done', to: 'purchases#done'
        post 'buy', to: 'purchases#buy'
      end
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get "select_category_index"
      get 'search'
      get 'all'
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  # resources :categories, only: [:index] do
  #   member do
  #     get 'parent'
  #     get 'child'
  #     get 'grandchild'
  #   end
  # end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_item, only:[:buy, :index]
  
  def index
    card = Card.find_by(user_id: current_user.id)
    # if card.blank?
    #   #登録された情報がない場合にカード登録画面に移動
    #   redirect_to new_card_path
    # else
    # Payjp.api_key = "sk_test_6d5bbe82c50db611a63aeefa"
    # #保管した顧客IDでpayjpから情報取得
    # customer = Payjp::Customer.retrieve(card.customer_id)
    # #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
    # @default_card_information = customer.cards.retrieve(card.card_id)
    # end
    unless @item.buyer_id.blank?
      redirect_to root_path and return
    end
    if current_user.destinations.blank?
      redirect_to new_destination_path
    elsif card.blank?
      #登録された情報がない場合にカード登録画面に移動
      redirect_to new_card_path
    else
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
    #保管した顧客IDでpayjpから情報取得
    customer = Payjp::Customer.retrieve(card.customer_id)
    #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
    @default_card_information = customer.cards.retrieve(card.card_id)
    end
    @destination = Destination.find_by(user_id: current_user.id)
  end

  def buy
    card = Card.find_by(user_id: current_user.id)
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
    Payjp::Charge.create(
    :amount => @item.price,
    :customer => card.customer_id, #顧客ID
    :currency => 'jpy' #日本円
  )
  @item.update( buyer_id: current_user.id) #seller_idに購入者のuser_idを追加し、製品のステータスをsold outに変更
  redirect_to root_path
  end

  private
  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/done.html.haml
%h2 購入が完了しました！
%p Apple MacBook Pro 13インチ
%p ¥135,000(送料込み)

app/views/purchases/index.html.haml
.header
  %h1.header__headerimage
    = link_to (image_tag src="logo.png", size: "300x81", class:"header__headerimage__logoimage"), items_path

.purc-main
  .singlemain
    %h2.buyhead 購入内容の確認
    .buycontent
      .buycontent__innner
        .buycontent__innner__itembox
          %h3.buycontent__innner__itembox__buyimage
            = image_tag @item.images[0].image.url, class: "postImage__itemimage", size: "100x120"
          .buycontent__innner__itembox__buytext
            %p.buycontent__innner__itembox__buytext__buyname
              =@item.name
            %p.buycontent__innner__itembox__buytext__buymoney
              ¥
              =@item.price
              （税込） 送料込み

    .total
      .total__totalinn
        .total__totalinn__totalbox
          %p.total__totalinn__totalbox__totaltext
            支払い金額
          %p.total__totalinn__totalbox__totalmoney
            ¥
            =@item.price

    .payment
      .payment__payinn
        .payment__payinn__paymentbox
          支払い方法
          .payment__payinn__paymentbox__paymentlink
            -# = link_to root_path, class: 'payment__payinn__paymentbox__paymentlink__paylinkicon' do
              -# = icon('fa', 'plus-circle')
              -# %span クレジットカード登録してください
            = "**** **** **** " + @default_card_information.last4
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year

    .address
      .address__addressinn
        .address__addressinn__addressbox
          配送先
          .address__addressinn__addressbox__addresslink
            -# = link_to root_path, class: "address__addressinn__addressbox__addresslink__addlinkicon" do
            -#   = icon('fa', 'plus-circle')
            .h2 
            〒
            = @destination.post_code 
            .h2      
            = @destination.prefecture.name
            = @destination.city
            = @destination.address
            = @destination.building_name 
            .h2 
            = @destination.family_name
            = @destination.first_name    

    .purcbtn
      -# = form_with url: root_path, method: :get do |f|
      -#   = f.submit '購入する', class: 'purcbtn__submitbtn'
      = form_tag(action: :buy, method: :post) do
        = hidden_field_tag :item, params[@item.id]
        %button{class: 'purcbtn__submitbtn'} 購入する

    -# .payfooter
    -#   %h1.payfooter__footerimage
    -#     = link_to (image_tag "logo-white", size: "140x60"), items_path