config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  # resources :items
  resources :users, only: [:show,:index]
  resources :images
  resources :destinations
  resources :purchases
  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'cards#pay'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :items do
  #   #Ajaxで動くアクションのルートを作成
  #   collection do
  #     get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
  #     get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
  #   end
  #   member do
  #     post 'buy', to: 'items#buy'
  #     get 'done', to: 'items#done'
  #   end
  # end

  resources :items do
    resources :purchases, only: [:index] do
      collection do
        get 'done', to: 'purchases#done'
        post 'buy', to: 'purchases#buy'
      end
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get "select_category_index"
      get 'search'
      get 'all'
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  # resources :categories, only: [:index] do
  #   member do
  #     get 'parent'
  #     get 'child'
  #     get 'grandchild'
  #   end
  # end

end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :status
  belongs_to_active_hash :cost
  belongs_to_active_hash :days
  belongs_to :category, dependent: :destroy
  belongs_to :brand, dependent: :destroy, optional: :true
  accepts_nested_attributes_for :brand
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  belongs_to :seller, class_name: "User", foreign_key: "seller_id"
  belongs_to :buyer, class_name: "User", foreign_key: "buyer_id", optional: true
  validates_associated :images, :category
  validates :seller_id, :description, :category_id, :status_id, :cost_id, :prefecture_id, :days_id, :images, presence: true
  validates :name, presence: true, length: {maximum: 40}
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }
  def self.search(search)
    return Item.all unless search
    Item.where('name LIKE(?)', "%#{search}%")
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :select_category_index, :search, :all]
  before_action :set_current_user_items,only:[:p_exhibiting,:p_soldout]
  before_action :set_user,only:[:p_exhibiting,:p_soldout]
  before_action :set_item, only:[:edit, :show, :destroy, :update, :purchase, :payment, :buy]
  require 'payjp'

  def index
    @parents = Category.where(ancestry: nil)
    # 新着アイテム
    @item = Item.limit(3).order('created_at DESC')
    # レディースアイテム
    @womencategory = Item.where(category_id: 1..199).order('created_at DESC').limit(3)
    # メンズアイテム
    @mencategory = Item.where(category_id: 200..345).order('created_at DESC').limit(3)
    # ベビー・キッズ
    @baby = Item.where(category_id: 346..480).order('created_at DESC').limit(3)
    # インテリア・住まい・小物
    @interia = Item.where(category_id: 481..624).order('created_at DESC').limit(3)
    # 本・音楽・ゲームアイテム
    @entertainment = Item.where(category_id: 625..684).order('created_at DESC').limit(3)
    # おもちゃ・ホビー・グッズ
    @hobby = Item.where(category_id: 685..797).order('created_at DESC').limit(3)
    # コスメ・香水・美容
    @beauty = Item.where(category_id: 798..897).order('created_at DESC').limit(3)
    # 家電・スマホ・カメラ
    @phone = Item.where(category_id: 898..983).order('created_at DESC').limit(3)
    # スポーツ・レジャー
    @sports = Item.where(category_id: 984..1092).order('created_at DESC').limit(3)
    # ハンドメイド
    @handmaid = Item.where(category_id: 1093..1146).order('created_at DESC').limit(3)
    # チケット
    @tickt = Item.where(category_id: 1147..1206).order('created_at DESC').limit(3)
    # 自動車・オートバイ
    @car = Item.where(category_id: 1207..1269).order('created_at DESC').limit(3)
    # その他
    @other = Item.where(category_id: 1270..1338).order('created_at DESC').limit(3)
    @items = Image.includes(:images).order('id DESC').limit(3)
  end

  def new
    @item = Item.new
    @item.images.new
    @item.build_brand
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      redirect_to new_item_path
    end
  end

  def show
    @item = Item.find(params[:id])
    @grandchild = Category.find(@item.category_id)
    @child = @grandchild.parent
    @parent = @child.parent
  end

  def edit
    @grandchild_category = @item.category
    @child_category = @grandchild_category.parent
    @category_parent = @child_category.parent
    @category = Category.find(params[:id])
    # 紐づく孫カテゴリーの親（子カテゴリー）の一覧を配列で取得
    @category_children = @item.category.parent.parent.children
    # 紐づく孫カテゴリーの一覧を配列で取得
    @category_grandchildren = @item.category.parent.children
    @category_parent_array = []
    @category_parent_array = Category.where(ancestry: nil)
    @category_children_array = []
    @category_children_array = Category.where(ancestry: @child_category.ancestry)
    @category_grandchildren_array = []
    @category_grandchildren_array = Category.where(ancestry: @grandchild_category.ancestry)
  end

  def update
    if @item.seller_id == current_user.id
      @item.category_id = nil unless params[:item][:category_id]
      if @item.update(item_params)
        redirect_to root_path
      else
        redirect_to edit_item_path(@item)
      end
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      render action: :show
    end
  end

  def all
    @parents = Category.where(ancestry: nil)    
    @items = Item.order("created_at DESC")
  end

  def search
    @parents = Category.where(ancestry: nil)
    @items = Item.search(params[:keyword]).order("created_at DESC")
  end

  def p_exhibiting #出品中のアクション
  end

  def p_soldout    #売却済みのアクション
  end

  def get_category_children
    @category_children = Category.find(params[:parent_name]).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  def buy
    card = Card.find_by(user_id: current_user.id)
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
    Payjp::Charge.create(
    :amount => @item.price,
    :customer => card.customer_id, #顧客ID
    :currency => 'jpy' #日本円
  )
    @item.update( buyer_id: current_user.id)
    redirect_to action: 'done' #完了画面に移動
  end

  def set_category_list
    @category_parent_array = Category.where(ancestry: nil)
  end

  def select_category_index
    @parents = Category.where(ancestry: nil)
    # カテゴリ名を取得するために@categoryにレコードをとってくる
    @category = Category.find_by(id: params[:format])
    # 親カテゴリーを選択していた場合の処理
    if @category.ancestry == nil
      # Categoryモデル内の親カテゴリーに紐づく孫カテゴリーのidを取得
      category = Category.find_by(id: params[:format]).indirect_ids
      # 孫カテゴリーに該当するitemsテーブルのレコードを入れるようの配列を用意
      # @items = []
      # # find_itemメソッドで処理
      # find_item(category.id)
      @items = Item.where(category_id: category).order("created_at DESC")
      # if @items.blank?
      #   redirect_to root_path
      # end
      # ancestry=category.ancestry
      # @items=ancestry.items

    # 孫カテゴリーを選択していた場合の処理
    elsif @category.ancestry.include?("/")
      # Categoryモデル内の親カテゴリーに紐づく孫カテゴリーのidを取得
      @items = Item.where(category_id: params[:format]).order("created_at DESC")
      # if @items.blank?
      #   redirect_to root_path
      # end

    # 子カテゴリーを選択していた場合の処理
    else
      category = Category.find_by(id: params[:format]).child_ids
      # 孫カテゴリーに該当するitemsテーブルのレコードを入れるようの配列を用意
      @items = Item.where(category_id: category).order("created_at DESC")
      # @items = []
      # # find_itemメソッドで処理
      # find_item(category)
      # if @items.blank?
      #   redirect_to root_path
      # end
    end
  end


  private
  def item_params
    params.require(:item).permit(:name, :description, :price, :cost_id, :days_id,:category_id,:status_id, :prefecture_id,
      images_attributes: [:id, :image, :_destroy], brand_attributes: [:id, :name]).merge(seller_id: current_user.id)
  end

  def set_current_user_items
    if user_signed_in?
      @items = current_user.items.includes(:seller,:buyer,:item_images)
    else
      redirect_to new_user_session_path
    end
  end

  def set_user
    @user = User.find(current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_baby.html.haml
-# ベビー・キッズ新着アイテムページ
- @baby.each do |item|
  .product__body__lists__list
    .product__body__lists__list__list-img
    - item.images.each_with_index do |image, index|
      - if index == 0
        = link_to image_tag("#{image.image.url}", width: '220', height: '200'), item_path(item.id), class: "product__body__lists__list__list-img__image" 
      - unless item.buyer_id.blank?
        .sold-tag
          .sold-tag__title sold out
    .product__body__lists__list__detail
      %h3.product__lists__list__detail-name 
        = item.name
        %ul.product__lists__list__detail-price
          %li.product__lists__list__detail-price__itemprice
            =item.price 
            円
          %li.product__lists__list__detail-price__itemstar
            %i.fa.fa-star.likeIcon
            0
        %p.product__lists__list__detail-tax (税込)

app/views/items/_beauty.html.haml
-# コスメ・香水・美容新着アイテムページ
- @beauty.each do |item|
  .product__body__lists__list
    .product__body__lists__list__list-img
    - item.images.each_with_index do |image, index|
      - if index == 0
        = link_to image_tag("#{image.image.url}", width: '220', height: '200'), item_path(item.id), class: "product__body__lists__list__list-img__image" 
      - unless item.buyer_id.blank?
        .sold-tag
          .sold-tag__title sold out
    .product__body__lists__list__detail
      %h3.product__lists__list__detail-name 
        = item.name
        %ul.product__lists__list__detail-price
          %li.product__lists__list__detail-price__itemprice
            =item.price 
            円
          %li.product__lists__list__detail-price__itemstar
            %i.fa.fa-star.likeIcon
            0
        %p.product__lists__list__detail-tax (税込)

app/views/items/_car.html.haml
-# 自動車・オートバイ新着アイテムページ
- @car.each do |item|
  .product__body__lists__list
    .product__body__lists__list__list-img
    - item.images.each_with_index do |image, index|
      - if index == 0
        = link_to image_tag("#{image.image.url}", width: '220', height: '200'), item_path(item.id), class: "product__body__lists__list__list-img__image" 
      - unless item.buyer_id.blank?
        .sold-tag
          .sold-tag__title sold out
    .product__body__lists__list__detail
      %h3.product__lists__list__detail-name 
        = item.name
        %ul.product__lists__list__detail-price
          %li.product__lists__list__detail-price__itemprice
            =item.price 
            円
          %li.product__lists__list__detail-price__itemstar
            %i.fa.fa-star.likeIcon
            0
        %p.product__lists__list__detail-tax (税込)

app/views/items/_handmaid.html.haml
-# ハンドメイド新着アイテムページ
- @handmaid.each do |item|
  .product__body__lists__list
    .product__body__lists__list__list-img
    - item.images.each_with_index do |image, index|
      - if index == 0
        = link_to image_tag("#{image.image.url}", width: '220', height: '200'), item_path(item.id), class: "product__body__lists__list__list-img__image" 
      - unless item.buyer_id.blank?
        .sold-tag
          .sold-tag__title sold out
    .product__body__lists__list__detail
      %h3.product__lists__list__detail-name 
        = item.name
        %ul.product__lists__list__detail-price
          %li.product__lists__list__detail-price__itemprice
            =item.price 
            円
          %li.product__lists__list__detail-price__itemstar
            %i.fa.fa-star.likeIcon
            0
        %p.product__lists__list__detail-tax (税込)

app/views/items/_hobby.html.haml
-# おもちゃ・ホビー・グッズ新着アイテムページ
- @hobby.each do |item|
  .product__body__lists__list
    .product__body__lists__list__list-img
    - item.images.each_with_index do |image, index|
      - if index == 0
        = link_to image_tag("#{image.image.url}", width: '220', height: '200'), item_path(item.id), class: "product__body__lists__list__list-img__image" 
      - unless item.buyer_id.blank?
        .sold-tag
          .sold-tag__title sold out
    .product__body__lists__list__detail
      %h3.product__lists__list__detail-name 
        = item.name
        %ul.product__lists__list__detail-price
          %li.product__lists__list__detail-price__itemprice
            =item.price 
            円
          %li.product__lists__list__detail-price__itemstar
            %i.fa.fa-star.likeIcon
            0
        %p.product__lists__list__detail-tax (税込)

app/views/items/_interia.html.haml
-# インテリア・住まい・小物新着アイテムページ
- @interia.each do |item|
  .product__body__lists__list
    .product__body__lists__list__list-img
    - item.images.each_with_index do |image, index|
      - if index == 0
        = link_to image_tag("#{image.image.url}", width: '220', height: '200'), item_path(item.id), class: "product__body__lists__list__list-img__image" 
      - unless item.buyer_id.blank?
        .sold-tag
          .sold-tag__title sold out
    .product__body__lists__list__detail
      %h3.product__lists__list__detail-name 
        = item.name
        %ul.product__lists__list__detail-price
          %li.product__lists__list__detail-price__itemprice
            =item.price 
            円
          %li.product__lists__list__detail-price__itemstar
            %i.fa.fa-star.likeIcon
            0
        %p.product__lists__list__detail-tax (税込)

app/views/items/_phone.html.haml
-# 家電・スマホ・カメラ新着アイテムページ
- @phone.each do |item|
  .product__body__lists__list
    .product__body__lists__list__list-img
    - item.images.each_with_index do |image, index|
      - if index == 0
        = link_to image_tag("#{image.image.url}", width: '220', height: '200'), item_path(item.id), class: "product__body__lists__list__list-img__image" 
      - unless item.buyer_id.blank?
        .sold-tag
          .sold-tag__title sold out
    .product__body__lists__list__detail
      %h3.product__lists__list__detail-name 
        = item.name
        %ul.product__lists__list__detail-price
          %li.product__lists__list__detail-price__itemprice
            =item.price 
            円
          %li.product__lists__list__detail-price__itemstar
            %i.fa.fa-star.likeIcon
            0
        %p.product__lists__list__detail-tax (税込)

app/views/items/_tickt.html.haml
-# チケット新着アイテムページ
- @tickt.each do |item|
  .product__body__lists__list
    .product__body__lists__list__list-img
    - item.images.each_with_index do |image, index|
      - if index == 0
        = link_to image_tag("#{image.image.url}", width: '220', height: '200'), item_path(item.id), class: "product__body__lists__list__list-img__image" 
      - unless item.buyer_id.blank?
        .sold-tag
          .sold-tag__title sold out
    .product__body__lists__list__detail
      %h3.product__lists__list__detail-name 
        = item.name
        %ul.product__lists__list__detail-price
          %li.product__lists__list__detail-price__itemprice
            =item.price 
            円
          %li.product__lists__list__detail-price__itemstar
            %i.fa.fa-star.likeIcon
            0
        %p.product__lists__list__detail-tax (税込)

app/views/items/all.html.haml
= render 'layouts/header'
.search
  .searchfield
  - @items.each do |item|
    .searchitem
      .searchitem__body
      - item.images.each_with_index do |image, index|
        - if index == 0
          = link_to image_tag("#{image.image.url}", width: '220', height: '200'), item_path(item.id), class: "searchitem__body__image" 
        - unless item.buyer_id.blank?
          .sold-tag
            .sold-tag__title sold out
      .searchitem__body__lists
        %h3.searchitem__body__lists__detail-name
          = item.name
          %ul.searchitem__body__lists__detail-price
            %li.searchitem__body__lists__detail-price__itemprice
              =item.price
              円
            %li.searchitem__body__lists__detail-price__itemstar
              %i.fa.fa-star.likeIcon
              0
          %p.searchitem__body__lists__detail-tax (税込)

= render 'layouts/footer'

app/views/items/ex.html.haml
ようこそ

app/views/items/index.html.haml
= render 'layouts/header'

.main
  .main__Visual
    .main-content
      %h1.main-content__title 人生を変えるフリマアプリ
      %p.main-content__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br/
        フリマアプリです
      .main-btn
        = link_to image_tag("download-on-app-store.png", class:"main-btn__A")
        = link_to image_tag("download-on-google.png", class:"main-btn__B")
  .main-introduction
    %h2.main-introduction__title FURIMAが選ばれる3つの理由
    %ul.main-introduction__lists
      %li.main-introduction__list
        = link_to image_tag("pict-reason-01.jpg", class:"main-introduction__list-img")
        %h1.main-introduction__list-number 1
        %h2.main-introduction__list-text
          %span 3分
          ですぐに出品
        %p.main-introduction__list-text1 スマホで入力するだけで簡単に出品できる！
      %li.main-introduction__list
        = link_to image_tag("pict-reason-02.jpg", class:"main-introduction__list-img")
        %h1.main-introduction__list-number 2
        %h2.main-introduction__list-text
          %span シンプル
          で使いやすい
        %p.main-introduction__list-text1 めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.main-introduction__list
        = link_to image_tag("pict-reason-03.jpg", class:"main-introduction__list-img")
        %h1.main-introduction__list-number 3
        %h2.main-introduction__list-text
          手数料
          %span 業界最安
        %p.main-introduction__list-text2 最大3%でお得に出品&amp;購入！
  .middle
    .middle__img
      .middle-content
        %h1.middle-content__title 会員数日本一位
        %p.middle-content__text
          FURIMAは、フリマアプリで最も人気。
          %br/
          出品・購入回数も業界最多です！
          %br/
          欲しかったあの商品にであるかもしれません。
        .middle-btn
          = link_to image_tag("download-on-app-store.png", class:"main-btn__A")
          = link_to image_tag("download-on-google.png", class:"main-btn__B")
  .main-introduction
    %h2.main-introduction__title FURIMAの特徴
    %ul.main-introduction__lists
      %li.main-introduction__list
        = link_to image_tag("icon-01.png", class:"main-introduction__list-img2")
        %h2.main-introduction__list-text3
          簡単に売り買いできる
        %p.main-introduction__list-text4 スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %li.main-introduction__list
        = link_to image_tag("icon-03.png", class:"main-introduction__list-img2")
        %h2.main-introduction__list-text3
          売上金は即日振込みに対応
        %p.main-introduction__list-text4 午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      %li.main-introduction__list
        = link_to image_tag("icon-04.png", class:"main-introduction__list-img2")
        %h2.main-introduction__list-text3
          様々な支払いに対応
        %p.main-introduction__list-text4 お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  .product
    %h1.product__head ピックアップアイテム
    .product__body
      %h2.product__body__body-title
        = link_to "新着アイテム", all_items_path
      .product__body__lists
        = render partial: "item", locals: {images: @items}

  .product
    %h1.product__head ピックアップカテゴリー
    - if @womencategory.exists?
      .product__body
        %h2.product__body__body-title
          = link_to "レディース新着アイテム", select_category_index_items_path(1), id: "1"        
        .product__body__lists
          = render partial: "women", locals: {images: @items}
    - if @mencategory.exists?          
      .product__body
        %h2.product__body__body-title
          = link_to "メンズ新着アイテム", select_category_index_items_path(200), id: "200"        
        .product__body__lists
          = render partial: "men", locals: {images: @items}
    - if @baby.exists?              
      .product__body
        %h2.product__body__body-title 
          = link_to "ベビー・キッズ新着アイテム", select_category_index_items_path(346), id: "346"
        .product__body__lists
          = render partial: "baby", locals: {images: @items}
    - if @interia.exists?          
      .product__body
        %h2.product__body__body-title
          = link_to "インテリア・住まい・小物新着アイテム", select_category_index_items_path(481), id: "481"        
        .product__body__lists
          = render partial: "interia", locals: {images: @items}
    - if @entertainment.exists?
      .product__body
        %h2.product__body__body-title
          = link_to "本・音楽・ゲームアイテム新着アイテム", select_category_index_items_path(625), id: "625"        
        .product__body__lists
          = render partial: "entertainment", locals: {images: @items}
    - if @hobby.exists?
      .product__body
        %h2.product__body__body-title
          = link_to "おもちゃ・ホビー・グッズ新着アイテム", select_category_index_items_path(685), id: "685"        
        .product__body__lists
          = render partial: "hobby", locals: {images: @items}
    - if @beauty.exists?
      .product__body
        %h2.product__body__body-title
          = link_to "コスメ・香水・美容新着アイテム", select_category_index_items_path(798), id: "798"
        .product__body__lists
          = render partial: "beauty", locals: {images: @items}
    - if @phone.exists?          
      .product__body
        %h2.product__body__body-title
          = link_to "家電・スマホ・カメラ新着アイテム", select_category_index_items_path(898), id: "898"        
        .product__body__lists
          = render partial: "phone", locals: {images: @items}
    - if @sports.exists?
      .product__body
        %h2.product__body__body-title
          = link_to "スポーツ・レジャー新着アイテム", select_category_index_items_path(984), id: "984"  
        .product__body__lists
          = render partial: "sports", locals: {images: @items}
    - if @handmaid.exists?          
      .product__body
        %h2.product__body__body-title
          = link_to "ハンドメイド新着アイテム", select_category_index_items_path(1093), id: "1093"     
        .product__body__lists
          = render partial: "handmaid", locals: {images: @items}
    - if @tickt.exists?              
      .product__body
        %h2.product__body__body-title
          = link_to " チケット新着アイテム", select_category_index_items_path(1147), id: "1147"      
        .product__body__lists
          = render partial: "tickt", locals: {images: @items}
    - if @car.exists?                
      .product__body
        %h2.product__body__body-title
          = link_to "自動車・オートバイ新着アイテム", select_category_index_items_path(1207), id: "1207"        
        .product__body__lists
          = render partial: "car", locals: {images: @items}
    - if @other.exists?               
      .product__body
        %h2.product__body__body-title
          = link_to "その他新着アイテム", select_category_index_items_path(1270), id: "1270"
        .product__body__lists
          = render partial: "other", locals: {images: @items}
  .banner
    .banner__img
      .banner-content
        %h1.banner-content__title だれでもかんたん、人生を変えるフリマアプリ
        %p.banner-content__text
          今すぐダウンロード！
        .banner-btn
          = link_to image_tag("download-on-app-store.png", class:"main-btn__A")
          = link_to image_tag("download-on-google.png", class:"main-btn__B")


/*出品ボタン*/
-# %a{:href => "#"}
= link_to new_item_path do
  .purchase-btn
    %span.purchase-btn__text 出品する
    =image_tag("icon_camera.png", class:"purchase-btn__icon")

= render 'layouts/footer'

app/views/items/search.html.haml
= render 'layouts/header'
.search
  .searchfield
    - if @items.blank?
      %span 該当する商品が見つかりません。検索条件を変えて、再度お試しください。
  - @items.each do |item|
    .searchitem
      .searchitem__body
      - item.images.each_with_index do |image, index|
        - if index == 0
          = link_to image_tag("#{image.image.url}", width: '220', height: '200'), item_path(item.id), class: "searchitem__body__image"
        - unless item.buyer_id.blank?
          .sold-tag
            .sold-tag__title sold out
      .searchitem__body__lists
        %h3.searchitem__body__lists__detail-name
          = item.name
          %ul.searchitem__body__lists__detail-price
            %li.searchitem__body__lists__detail-price__itemprice
              =item.price
              円
            %li.searchitem__body__lists__detail-price__itemstar
              %i.fa.fa-star.likeIcon
              0
          %p.searchitem__body__lists__detail-tax (税込)

= render 'layouts/footer'