config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  # resources :items
  resources :users, only: [:show,:index]
  resources :images
  resources :destinations
  resources :purchases
  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'cards#pay'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :items do
  #   #Ajaxで動くアクションのルートを作成
  #   collection do
  #     get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
  #     get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
  #   end
  #   member do
  #     post 'buy', to: 'items#buy'
  #     get 'done', to: 'items#done'
  #   end
  # end

  resources :items do
    resources :purchases, only: [:index] do
      collection do
        get 'done', to: 'purchases#done'
        post 'buy', to: 'purchases#buy'
      end
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get "select_category_index"
      get 'search'
      get 'all'
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  # resources :categories, only: [:index] do
  #   member do
  #     get 'parent'
  #     get 'child'
  #     get 'grandchild'
  #   end
  # end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
  validates :name, presence: true
  validates :ancestry, exclusion: { in: ["/"] }
end

app/models/cost.rb
class Cost < ActiveHash::Base
  self.data = [
    {id: 1,name: '送料込み(出品者負担)'},{id: 2,name: '着払い(購入者負担)'}
  ]
end

app/models/days.rb
class Days < ActiveHash::Base
  self.data = [
     {id: 1,name: '1~2日で発送'}, {id: 2,name:'2~3日で発送'}, {id: 3,name:'4~7日で発送'}
  ]
end

app/models/destination.rb
class Destination < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to_active_hash :prefecture

  validates :user_id, presence: true
  validates :family_name, presence: true, format: { with:/\A[ぁ-んァ-ン一-龥]/}
  validates :first_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/}
  validates :family_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/}
  validates :first_name_kana,  presence: true, format: { with: /\A[ァ-ヶー－]+\z/}
  validates :post_code, format: { with: /\A\d{7}\z/ }, presence: true
  validates :prefecture_id, presence: true
  validates :city, presence: true
  validates :address, presence: true
  validates :phone_number, format: { with: /\A[0-9]+\z/}, allow_blank: true
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :status
  belongs_to_active_hash :cost
  belongs_to_active_hash :days
  belongs_to :category, dependent: :destroy
  belongs_to :brand, dependent: :destroy, optional: :true
  accepts_nested_attributes_for :brand
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  belongs_to :seller, class_name: "User", foreign_key: "seller_id"
  belongs_to :buyer, class_name: "User", foreign_key: "buyer_id", optional: true
  validates_associated :images, :category
  validates :seller_id, :description, :category_id, :status_id, :cost_id, :prefecture_id, :days_id, :images, presence: true
  validates :name, presence: true, length: {maximum: 40}
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }
  def self.search(search)
    return Item.all unless search
    Item.where('name LIKE(?)', "%#{search}%")
  end

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}, {id: 48, name: '未定'}
  ]
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    {id: 1,name: '新品、未使用'},{id: 2,name: '未使用に近い'},
    {id: 3,name: '目立った傷や汚れなし'},{id: 4,name: 'やや傷や汚れあり'},
    {id: 5,name: '傷や汚れあり'},{id: 6,name: '全体的に状態が悪い'}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, :family_name, :first_name, :family_name_kana, :first_name_kana, :birth_day, presence: true

  has_many :destinations, dependent: :destroy
  has_many :cards, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :selling_items, -> { where("buyer_id is NULL") }, foreign_key: "seller_id", class_name: "Item"
  has_many :bought_items, class_name: "Item", foreign_key: "buyer_id"
  has_many :sold_items, -> { where("buyer_id is not NULL") }, foreign_key: "seller_id", class_name: "Item"

  # パスワード英字数字１文字かつ７文字以上のバリデーション↓
  validates :password, format: { with:/\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{7,100}+\z/i}
  # 全角のバリデーション↓
  validate :name_em
  validate :name_kana_em
  # メールアドレスのバリデーション↓
  validate :valid_email?


  def valid_email?
    return if email.blank? || email =~ /^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
    # blank?はblankであれば"true"でblankでなければ"flase"を返す
    # ||は"または"であり左側が"false"なら右側を"return"する
    # つまり"email.blank?"が"false(ブランクではない)"場合、"email"を正規表現にかけるということになる
  end

  # 別に使用予定の可能性があるためいったんコメントアウト
  
  # def encrypted_password
  #   # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a

    # return if password.blank? || password =~ /^(?=.*?[a-zA-Z])(?=.*?[0-9]).{7,70}$/

  #   # blank?-値がない状態がture
  #   errors.add :password, "は英字と数字をそれぞれ1文字以上含める必要があります"
  #   # password.blank? || password =~ のどちらも"false"だからエラーになり、エラー表示される
  # end

  def name_em
    if !(family_name =~ /^[ぁ-んァ-ン一-龥]/)
      if !(first_name =~ /^[ぁ-んァ-ン一-龥]/)
        errors.add :family_name, "は全角で入力してください"
        errors.add :first_name, "は全角で入力してください"
      else
        errors.add :family_name, "は全角で入力してください"
      end
    elsif !(first_name =~ /^[ぁ-んァ-ン一-龥]/)
      errors.add :first_name, "は全角で入力してください"
    else
      return
    end
  end

  def name_kana_em
    if !(family_name_kana =~ /^([ァ-ン]|ー)+$/)
      if !(first_name_kana =~ /^([ァ-ン]|ー)+$/)
        errors.add :family_name_kana, "は全角カタカナで入力してください"
        errors.add :first_name_kana, "は全角カタカナで入力してください"
      else
        errors.add :family_name_kana, "は全角カタカナで入力してください"
      end
    elsif !(first_name_kana =~ /^([ァ-ン]|ー)+$/)
      errors.add :first_name_kana, "は全角カタカナで入力してください"
    else
      return
    end
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/categorys_helper.rb
module CategorysHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.haml
-if model.errors.any?
  .alert
    %ul
      -model.errors.full_messages.each do |message|
        %li= message

app/views/layouts/_footer.html.haml
/*フッダー*/
.main-footer
  %ul.main-footer__contents
    %li.main-footer__contents__content
      %h2.main-footer__contents__content__head FURIMAについて
      %ul
        %li
          = link_to "会社概要（運営会社)"
        %li
          = link_to "ライバシーポリシー"
        %li
          = link_to "FURIMA利用規約"
        %li
          = link_to "ポイントに関する特約"
    %li.main-footer__contents__content
      %h2.main-footer__contents__content__head FURIMAを見る
      %ul
        %li
          = link_to "カテゴリー一覧"
        %li
          = link_to "ブランド一覧"
    %li.main-footer__contents__content
      %h2.main-footer__contents__content__head ヘルプ&ガイド
      %ul
        %li
          = link_to "URIMAガイド"
        %li
          = link_to "FURIMAロゴ利用ガイドライン"
        %li
          = link_to "お知らせ"
  .main-footer__logo
    =link_to image_tag("logo-white.png", width: "160")
  %p © FURIMA

app/views/layouts/_header.html.haml
/*ヘッダー*/
.main-header
  .main-header__inner
    .main-header__inner__main
      %h1.main-header__inner__main__icon
        =link_to image_tag("logo.png", width: "140"), root_path
      .main-header__inner__main__searchbox
        = form_with(url: search_items_path, local: true, method: :get, class: "form") do |form|
          = form.text_field :keyword, placeholder: "キーワードから探す", class: "searchInput.searchbox--input"
          = button_tag type: 'submit', class: 'main-header__inner__main__searchbox__icon' do
            %i.fas.fa-search
    .main-header__inner__nav
      %ul.category-wrap
        %li.category
          %p.category-list-title カテゴリー検索
          %ul.parent-wrap
            - @parents.each do |parent|
              %li.parent
                = link_to "#{parent.name}", select_category_index_items_path(parent.id), class: "category__parent--name",id: "#{parent.id}"
                %ul.child-wrap
                  - parent.children.each do |child|
                    %li.child
                      = link_to "#{child.name}", select_category_index_items_path(child.id), class: "category__child--name",id: "#{child.id}"
                      %ul.grandchild-wrap
                        - child.children.each do |grandchild|
                          %li.grandchild
                            = link_to "#{grandchild.name}", select_category_index_items_path(grandchild.id), class: "category__grandchild--name",id: "#{grandchild.id}"
        .main-header__inner__nav__listleft__item
          -# = link_to "ブランド"
        %ul.brandsPulldown.displayNone
      %ul.main-header__inner__nav__listright
        - if user_signed_in?
          %li.main-header__inner__nav__listright__item.listright__item--login
            = link_to "ログアウト", destroy_user_session_path, method: :delete
          %li.main-header__inner__nav__listright__item.listright__item--new
            = link_to "新規商品登録", new_item_path
          %li.main-header__inner__nav__listright__item.listright__item--mypage
            = link_to "マイページ", user_path(current_user)
        - else
          %li.main-header__inner__nav__listright__item.listright__item--login
            = link_to "ログイン", new_user_session_path
          %li.main-header__inner__nav__listright__item.listright__item--new
            = link_to "新規会員登録", new_user_registration_path


    -# .main-header__inner__nav
    -#   %ul.main-header__inner__nav__listleft
    -#     %li.main-header__inner__nav__listleft__item.listleft__item--first
    -#       = link_to "カテゴリー"
    -#     %li.main-header__inner__nav__listleft__item
    -#       = link_to "ブランド"
    -#       %ul.brandsPulldown.displayNone
    -#   %ul.main-header__inner__nav__listright
    -#     - if user_signed_in?
    -#       %li.main-header__inner__nav__listright__item.listright__item--login
    -#         = link_to "ログアウト", destroy_user_session_path, method: :delete
    -#       %li.main-header__inner__nav__listright__item.listright__item--new
    -#         = link_to "新規商品登録", new_item_path
    -#       %li.main-header__inner__nav__listright__item.listright__item--mypage
    -#         = link_to "マイページ", user_path(current_user)
    -#     - else
    -#       %li.main-header__inner__nav__listright__item.listright__item--login
    -#         = link_to "ログイン", new_user_session_path
    -#       %li.main-header__inner__nav__listright__item.listright__item--new
    -#         = link_to "新規会員登録", new_user_registration_path

app/views/layouts/application.html.haml
-# <!DOCTYPE html>
-# <html>
-#   <head>
-#     <title>FreemarketSample76a</title>
-#     <%= csrf_meta_tags %>
-#     <%= csp_meta_tag %>

-#     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
-#     <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
-#   </head>

-#   <body>
-#     <%= yield %>
-#   </body>
-# </html>

!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title furima
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    -# = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
  %body
    = yield